language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env:
        - COVERAGE=yes
        - ANALYSIS=yes
    - php: 7.4
    - php: 8.0snapshot
  fast_finish: true

before_install:
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini || true; fi;
  - if [[ $TRAVIS_REPO_SLUG = webmozart/path-util ]]; then cp .composer-auth.json ~/.composer/auth.json; fi;
  - travis_retry composer self-update

install: travis_retry composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script: if [[ $COVERAGE = yes ]]; then vendor/bin/simple-phpunit --verbose --coverage-clover=coverage.clover; else vendor/bin/simple-phpunit --verbose; fi

after_script: if [[ $COVERAGE = yes ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
